"""add_instructor_review_and_lesson_reminders

Revision ID: 11803e318d74
Revises: 17ed7910b477
Create Date: 2026-03-23 13:36:21.516093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11803e318d74'
down_revision = '17ed7910b477'
branch_labels = None
depends_on = None


def upgrade():
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing_tables = inspector.get_table_names()

    if 'instructor_review' not in existing_tables:
        op.create_table('instructor_review',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('instructor_id', sa.Integer(), nullable=False),
        sa.Column('student_id', sa.Integer(), nullable=False),
        sa.Column('rating', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(length=100), nullable=True),
        sa.Column('comment', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['instructor_id'], ['user.id'], ),
        sa.ForeignKeyConstraint(['student_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('instructor_id', 'student_id', name='uq_instructor_student_review')
        )

    lesson_columns = [c['name'] for c in inspector.get_columns('lesson')]
    with op.batch_alter_table('lesson', schema=None) as batch_op:
        if 'reminder_24h_sent' not in lesson_columns:
            batch_op.add_column(sa.Column('reminder_24h_sent', sa.Boolean(), nullable=True))
        if 'reminder_1h_sent' not in lesson_columns:
            batch_op.add_column(sa.Column('reminder_1h_sent', sa.Boolean(), nullable=True))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.drop_column('reminder_1h_sent')
        batch_op.drop_column('reminder_24h_sent')

    op.drop_table('instructor_review')
    # ### end Alembic commands ###
