"""add test_passed to student_profile

Revision ID: 1f5891a3d27c
Revises: 400d87b365b0
Create Date: 2026-03-22 14:29:14.757106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f5891a3d27c'
down_revision = '400d87b365b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test_passed', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('test_passed_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_profile', schema=None) as batch_op:
        batch_op.drop_column('test_passed_date')
        batch_op.drop_column('test_passed')

    # ### end Alembic commands ###
