"""add email_confirmed and confirmed_at to user

Revision ID: 21b0ab7ae92d
Revises: bd58ef33dbfd
Create Date: 2026-03-25 17:49:28.403072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21b0ab7ae92d'
down_revision = 'bd58ef33dbfd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_confirmed', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('confirmed_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('confirmed_at')
        batch_op.drop_column('email_confirmed')

    # ### end Alembic commands ###
