"""Add NotificationPreference model and instructor phone

Revision ID: 400d87b365b0
Revises: 833744b85cf3
Create Date: 2026-03-22 13:37:34.225480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '400d87b365b0'
down_revision = '833744b85cf3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_preference',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email_enabled', sa.Boolean(), nullable=True),
    sa.Column('whatsapp_enabled', sa.Boolean(), nullable=True),
    sa.Column('notify_lesson_booked', sa.Boolean(), nullable=True),
    sa.Column('notify_lesson_cancelled', sa.Boolean(), nullable=True),
    sa.Column('notify_feedback', sa.Boolean(), nullable=True),
    sa.Column('notify_payment', sa.Boolean(), nullable=True),
    sa.Column('notify_skill_update', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('instructor_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instructor_profile', schema=None) as batch_op:
        batch_op.drop_column('phone')

    op.drop_table('notification_preference')
    # ### end Alembic commands ###
