"""Add availability location and pickup fields

Revision ID: 868506943d82
Revises: 6435139eb084
Create Date: 2026-03-22 10:26:55.907908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '868506943d82'
down_revision = '6435139eb084'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instructor_availability',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instructor_id', sa.Integer(), nullable=True),
    sa.Column('day_of_week', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.ForeignKeyConstraint(['instructor_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('instructor_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('latitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('longitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('service_radius_km', sa.Float(), nullable=True))

    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pickup_address', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('pickup_lat', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('pickup_lng', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.drop_column('pickup_lng')
        batch_op.drop_column('pickup_lat')
        batch_op.drop_column('pickup_address')

    with op.batch_alter_table('instructor_profile', schema=None) as batch_op:
        batch_op.drop_column('service_radius_km')
        batch_op.drop_column('longitude')
        batch_op.drop_column('latitude')
        batch_op.drop_column('address')

    op.drop_table('instructor_availability')
    # ### end Alembic commands ###
