"""add_in_app_notification_instructor_payout_sms

Revision ID: bd58ef33dbfd
Revises: 11803e318d74
Create Date: 2026-03-23 13:59:15.331867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd58ef33dbfd'
down_revision = '11803e318d74'
branch_labels = None
depends_on = None


def _table_exists(bind, name):
    insp = sa.inspect(bind)
    return name in insp.get_table_names()


def _column_exists(bind, table, column):
    insp = sa.inspect(bind)
    return any(c['name'] == column for c in insp.get_columns(table))


def upgrade():
    bind = op.get_bind()

    if not _table_exists(bind, 'in_app_notification'):
        op.create_table('in_app_notification',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(length=150), nullable=False),
        sa.Column('message', sa.Text(), nullable=False),
        sa.Column('category', sa.String(length=30), nullable=True),
        sa.Column('is_read', sa.Boolean(), nullable=True),
        sa.Column('link', sa.String(length=255), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id')
        )

    if not _table_exists(bind, 'instructor_payout'):
        op.create_table('instructor_payout',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('instructor_id', sa.Integer(), nullable=False),
        sa.Column('amount', sa.Float(), nullable=False),
        sa.Column('currency', sa.String(length=3), nullable=True),
        sa.Column('status', sa.String(length=20), nullable=True),
        sa.Column('period_start', sa.Date(), nullable=True),
        sa.Column('period_end', sa.Date(), nullable=True),
        sa.Column('lessons_count', sa.Integer(), nullable=True),
        sa.Column('stripe_transfer_id', sa.String(length=255), nullable=True),
        sa.Column('stripe_connect_account_id', sa.String(length=255), nullable=True),
        sa.Column('notes', sa.String(length=255), nullable=True),
        sa.Column('processed_by_id', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('processed_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['instructor_id'], ['user.id'], ),
        sa.ForeignKeyConstraint(['processed_by_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id')
        )

    if not _column_exists(bind, 'instructor_profile', 'stripe_connect_account_id'):
        with op.batch_alter_table('instructor_profile', schema=None) as batch_op:
            batch_op.add_column(sa.Column('stripe_connect_account_id', sa.String(length=255), nullable=True))

    if not _column_exists(bind, 'notification_preference', 'sms_enabled'):
        with op.batch_alter_table('notification_preference', schema=None) as batch_op:
            batch_op.add_column(sa.Column('sms_enabled', sa.Boolean(), nullable=True))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification_preference', schema=None) as batch_op:
        batch_op.drop_column('sms_enabled')

    with op.batch_alter_table('instructor_profile', schema=None) as batch_op:
        batch_op.drop_column('stripe_connect_account_id')

    op.drop_table('instructor_payout')
    op.drop_table('in_app_notification')
    # ### end Alembic commands ###
